<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\node\NodeInterface;

/**
 * Implements hook_theme().
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 *
 * @return array
 */
function community_dashboard_theme($existing, $type, $theme, $path) {
  return [
    'admin_dashboard' => [
      'variables' => ['data' => NULL],
    ],
    'admin_dashboard_menu' => [
      'variables' => ['data' => NULL],
    ]
  ];
}
