<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\node\NodeInterface;

/**
 * Implements hook_theme().
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 *
 * @return array
 */
function community_builder_theme($existing, $type, $theme, $path) {
  return [
    'hero_banner_block' => [
      'variables' => ['data' => NULL],
    ],
  ];
}

/**
 * Implements hook_element_info_alter().
 * @param array $types
 */
function community_builder_element_info_alter(array &$types) {
  // Attach our extra CSS for toolbar icons.
  if (isset($types['toolbar'])) {
    $types['toolbar']['#attached']['library'][] = 'community_builder/toolbar';
  }
}

/**
 * Implements hook_form_alter().
 * @param array $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 *
 */
function community_builder_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  if ($form_id === 'node_posts_form') {
    // Set default value for community.
    $community = \Drupal::request()->query->get('community');
    if ($community) {
      $form['field_community']['widget']['#default_value'] = $community;
      $form['field_community']['widget']['#attributes']['disabled'] = 'disabled';
      // Hide widget when community already selected.
      //    $form['field_community']['#attributes']['style'] = 'display:none';
    }
  }
  if ($form_id === 'node_posts_edit_form') {
    $form['field_community']['widget']['#attributes']['disabled'] = 'disabled';
    // Hide widget when community already selected.
    //    $form['field_community']['#attributes']['style'] = 'display:none';
  }
}

/**
 * Implements hook_ENTITY_TYPE_insert() for node entities.
 * @param \Drupal\node\NodeInterface $node
 *
 */
function community_builder_node_insert(NodeInterface $node) {
//  $groupEntity = [];
//  $groupId = $node->get('field_community')->value;
//  $type = $groupEntity->getGroupType()->id() . '-group_node-' . $node->getType();
//  $groupContentEntity = \Drupal\group\Entity\GroupContent::create([
//    'gid' => $groupEntity->id(),
//    'entity_id' => $node->id(),
//    'type' => $type,
//  ]);
//  $groupContentEntity->save();
}
